### ISSUE TITLE
Some feedback on the repo

### ISSUE THREAD

**Issue by LunarPenguin** [Eviepayne/digitalcriminal-install#1]
Hello, originally i wanted to respond to your issue on the `DigitalCriminal/OnlyFans` repo but i decided it would be better suited in a separate issue in this repo. therefore you can see this as a response to your issue `#1485` on the `DigitalCriminal/OnlyFans` repo.

>Nice work. i have not tested it myself but i did have a quick look at the repo and one suggestion i would have is to explain a little better what the script is designed to to.

>- Right now your repo has no description, adding one helps to inform users what the repo does. for example the description of this repo is: `Scrape all the media from an OnlyFans account - Updated regularly`
>- Your `readme.md` jumps right into the meat and potatoes of the usage of the script. maybe you could start with a header and a small bit of introductory text that explain what the script does and does not do. this expands upon point 1 above
>- This is a real nitpicky point but you could possibly improve the `readme.md` a bit by using headers but as i said this is really a nitpicky point as the `readme.md` seems fine as-is.

**Comment by Eviepayne** [comment]
Fair. I did kinda haphazardly just throw some stuff together.
I'll improve the read me and make it clear what the script does (and doesn't) do.

**Comment by Eviepayne** [comment]
Readme should be more clear and more pleasing to the eye.

**Comment by LunarPenguin** [comment]
> Readme should be more clear and more pleasing to the eye.

Looks good!
