### ISSUE TITLE
Force close

### ISSUE THREAD

**Issue by lanzjose** [Eviepayne/digitalcriminal-install#2]
I cannot open the script. I just force closes :(

**Comment by Eviepayne** [comment]
In explorer hold shift + right click "open powershell here"
then run ./DCinstall.ps1
send the error message

**Comment by lanzjose** [comment]
./DCinstall.ps1 : O arquivo D:\DCinstall.ps1 não pode ser carregado. O arquivo D:\DCinstall.ps1 não está assinado
digitalmente. Não é possível executar este script no sistema atual. Para obter mais informações sobre como executar
scripts e definir a política de execução, consulte about_Execution_Policies at
https://go.microsoft.com/fwlink/?LinkID=135170.
No linha:1 caractere:1
+ ./DCinstall.ps1
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ErrodeSegurança: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
    
Auto Translate

./DCinstall.ps1 : The file D:\DCinstall.ps1 cannot be loaded. The file D:\DCinstall.ps1 is not digitally signed.
is not digitally signed. You cannot run this script on the current system. For more information on how to run
scripts and set the execution policy, see about_Execution_Policies at
https://go.microsoft.com/fwlink/?LinkID=135170.
On line:1 character
+ ./DCinstall.ps1
+ ~~~~~~~~~~~~~~~
    + CategoryInfo : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

--------------------
(sorry... i was ill and away from my pc last week)
