### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by MrRawrrino89** [Eviepayne/digitalcriminal-install#3]
Trying to install your script, pressing y on the confirm part, but then it all auto closes pretty fast and nothing appears in the temp file? anything i should know?

**Comment by Eviepayne** [comment]
download the dcinstall.ps1
delete C:\temp\onlyfans
delete the onlyfans folder in the current directory if it's there.
put the dcinstall.ps1 file where you want the onlyfans folder to be.
then try running the script.

**Comment by MrRawrrino89** [comment]
hmm yeah so i got it in a folder where i want it but when i press y on the powershell thing inside it, it says its installing chocolety etc but it just auto closes down and nothing but a text file appears in that folder?

**Comment by Eviepayne** [comment]
```
    switch ( $rep )
    {
        "y" { Install-Packages
            # need to start a new powershell environment
            Store-Location("newenv")
            stop-process -Id $PID
            }
    default { write-host "Exiting..."
            $PID| out-file C:\temp\onlyfans\pid.txt
            stop-process -Id $PID
            }
```
I assume this is where you're talking about. you need to enter "y" specifically. Anything else will quit the script.

**Comment by Eviepayne** [comment]
on line
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

Can you add `> log.txt `
rerun the script and post the contents of that file.
